name: asciidoc-markdown convert

on:
  push:
    tags:
      - v*
    

jobs:
  adoc-export-convert-info:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo code
        uses: actions/checkout@v2
     
      - name: Ruby init  
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      
      - name: Asciidoctor init
        uses: reitzig/actions-asciidoctor@v2.0.0
        with:
          version: 2.0.10
      
      - name: Asciidoctor version check
        run: asciidoctor --version

      - name: Convert to docbook
        run: asciidoctor -b docbook ./docs/pandoc-test/*.adoc
      
      - name: Convert via Pandoc
        uses: maxheld83/pandoc-action@v2
        with: 
          args: "-f docbook -t markdown_strict docs/pandoc-test/testdoc.xml -o ./docs/testdocmarkdown.md"

      - name: post commit and push    
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m $GITHUB_SHA
          git push -u origin master