name: asciidoc-markdown convert

on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  adoc-convert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      
      - name: Asciidoctor Setup
        uses: reitzig/actions-asciidoctor@v2.0.0
        with:
          version: 2.0.10
      
      - name: Asciidoctor version check
        run: asciidoctor --version

      - name: Convert to docbook
        run: asciidoctor -b docbook docs/pandoc-test/testdoc.adoc
