name: asciidoc-markdown convert

on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Asciidoctor Setup
        uses: reitzig/actions-asciidoctor@v2.0.0
        with:
          version: 2.0.10
      
      - name: Asciidoctor version check
      - run: asciidoctor --version
